"""
SQLAlchemy ORM model for PatchCandidate.

Each PatchCandidate is a repair attempt generated for a RepairRun.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Enum, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class TestStatus(str, enum.Enum):
    """Whether a patch candidate passed the test suite."""

    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    ERROR = "ERROR"


class PatchCandidate(Base):
    """A candidate patch generated by the repair engine."""

    __tablename__ = "patch_candidates"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    run_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("repair_runs.id"), nullable=False
    )
    # Human-readable summary of what the patch changes.
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Unified diff string.
    diff: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Score assigned by the AI model (0.0 – 1.0).
    model_score: Mapped[float] = mapped_column(Float, default=0.0)
    # Result of running the test suite against this patch.
    test_status: Mapped[TestStatus] = mapped_column(
        Enum(TestStatus), default=TestStatus.PENDING, nullable=False
    )
    # Final combined ranking score.
    final_score: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    run: Mapped["RepairRun"] = relationship("RepairRun", back_populates="patches")  # noqa: F821

    def __repr__(self) -> str:
        return f"<PatchCandidate id={self.id!r} test_status={self.test_status}>"

